export const users = [
    {
      id: 1,
      PersonName: "Erlan Zhumabekov",
      Avatar: "src/assets/pfp_1.svg",
      email: "erlan@example.com",
      login: "erlan_z",
      password: "securepassword1",
      favoriteUsers: [2, 3],
      posts: [
        {
          PubDate: "2024-03-01",
          Rating: 5,
          Commentary: "This is awesome!",
          Topic: "Adventure",
          isLiked: false,
          likeCount: 0,
        },
      ],
    },
    {
      id: 2,
      PersonName: "Aliya Sagyndykova",
      Avatar: "src/assets/pfp_2.svg",
      email: "aliya@example.com",
      login: "aliya_s",
      password: "securepassword2",
      favoriteUsers: [1, 4],
      posts: [
        {
          PubDate: "2023-09-08",
          Rating: 4,
          Commentary: "I lost the exit.",
          Topic: "Nature",
          isLiked: false,
          likeCount: 1,
        },
        {
          PubDate: "2024-01-15",
          Rating: 5,
          Commentary: "Nature is healing.",
          Topic: "Nature",
          isLiked: false,
          likeCount: 2,
        },
      ],
    },
    {
      id: 3,
      PersonName: "Saule Temirkhanova",
      Avatar: "src/assets/pfp_3.svg",
      email: "saule@example.com",
      login: "saule_t",
      password: "securepassword3",
      favoriteUsers: [1, 2],
      posts: [
        {
          PubDate: "2024-11-21",
          Rating: 5,
          Commentary: "Emotions overload!",
          Topic: "Fashion",
          isLiked: false,
          likeCount: 0,
        },
      ],
    },
    {
      id: 4,
      PersonName: "Serik Kenzhebek",
      Avatar: "src/assets/pfp_4.svg",
      email: "serik@example.com",
      login: "serik_k",
      password: "securepassword4",
      favoriteUsers: [2, 3],
      posts: [
        {
          PubDate: "2024-04-10",
          Rating: 3,
          Commentary: "Needs improvement",
          Topic: "Adventure",
          isLiked: false,
          likeCount: 1,
        },
      ],
    },
    {
      id: 5,
      PersonName: "Zhanna Seitkhanova",
      Avatar: "src/assets/pfp_5.svg",
      email: "zhanna@example.com",
      login: "zhanna_s",
      password: "securepassword5",
      favoriteUsers: [1, 4],
      posts: [
        {
          PubDate: "2024-08-15",
          Rating: 4,
          Commentary: "Fantastic visuals!",
          Topic: "Modern",
          isLiked: false,
          likeCount: 2,
        },
      ],
    },
    {
      id: 6,
      PersonName: "Daulet Khan",
      Avatar: "src/assets/pfp_6.svg",
      email: "daulet@example.com",
      login: "daulet_k",
      password: "securepassword6",
      favoriteUsers: [5, 7],
      posts: [
        {
          PubDate: "2024-06-06",
          Rating: 3,
          Commentary: "A bit slow.",
          Topic: "Nature",
          isLiked: false,
          likeCount: 4,
        },
      ],
    },
    {
      id: 7,
      PersonName: "Miras Altynbek",
      Avatar: "src/assets/pfp_7.svg",
      email: "miras@example.com",
      login: "miras_a",
      password: "securepassword7",
      favoriteUsers: [3, 6],
      posts: [
        {
          PubDate: "2024-01-01",
          Rating: 5,
          Commentary: "Unforgettable journey.",
          Topic: "Adventure",
          isLiked: false,
          likeCount: 3,
        },
      ],
    },
    {
      id: 8,
      PersonName: "Olzhas Tleubergen",
      Avatar: "src/assets/pfp_8.svg",
      email: "olzhas@example.com",
      login: "olzhas_t",
      password: "securepassword8",
      favoriteUsers: [1, 5],
      posts: [
        {
          PubDate: "2024-06-12",
          Rating: 4,
          Commentary: "Such a peaceful vibe.",
          Topic: "Nature",
          isLiked: false,
          likeCount: 1,
        },
      ],
    },
    {
      id: 9,
      PersonName: "Nurlan Bekzhan",
      Avatar: "src/assets/pfp_9.svg",
      email: "nurlan@example.com",
      login: "nurlan_b",
      password: "securepassword9",
      favoriteUsers: [7, 8],
      posts: [
        {
          PubDate: "2024-08-29",
          Rating: 2,
          Commentary: "Could be better.",
          Topic: "Adventure",
          isLiked: false,
          likeCount: 7,
        },
      ],
    },
    {
      id: 10,
      PersonName: "Asel Amanzholova",
      Avatar: "src/assets/pfp_10.svg",
      email: "asel@example.com",
      login: "asel_a",
      password: "securepassword10",
      favoriteUsers: [4, 6],
      posts: [
        {
          PubDate: "2024-11-09",
          Rating: 5,
          Commentary: "Pure joy!",
          Topic: "Modern",
          isLiked: false,
          likeCount: 5,
        },
      ],
    },
    {
      id: 11,
      PersonName: "Robert Nurman",
      Avatar: "src/assets/pfp_11.svg",
      email: "robert@example.com",
      login: "robert_n",
      password: "securepassword11",
      favoriteUsers: [10, 3],
      posts: [
        {
          PubDate: "2024-04-02",
          Rating: 3,
          Commentary: "Interesting concept.",
          Topic: "Nature",
          isLiked: false,
          likeCount: 2,
        },
      ],
    },
    {
      id: 12,
      PersonName: "Ainur Sarsenova",
      Avatar: "src/assets/pfp_12.svg",
      email: "ainur@example.com",
      login: "ainur_s",
      password: "securepassword12",
      favoriteUsers: [2, 8],
      posts: [
        {
          PubDate: "2024-03-07",
          Rating: 4,
          Commentary: "Great atmosphere!",
          Topic: "Fashion",
          isLiked: false,
          likeCount: 1,
        },
      ],
    },
    {
      id: 13,
      PersonName: "Daniyar Baitasov",
      Avatar: "src/assets/pfp_13.svg",
      email: "daniyar@example.com",
      login: "daniyar_b",
      password: "securepassword13",
      favoriteUsers: [5, 9],
      posts: [
        {
          PubDate: "2024-02-26",
          Rating: 2,
          Commentary: "Too chaotic.",
          Topic: "Adventure",
          isLiked: false,
          likeCount: 0,
        },
      ],
    },
    {
      id: 14,
      PersonName: "Altynai Bekova",
      Avatar: "src/assets/pfp_14.svg",
      email: "altynai@example.com",
      login: "altynai_b",
      password: "securepassword14",
      favoriteUsers: [6, 11],
      posts: [
        {
          PubDate: "2024-12-16",
          Rating: 5,
          Commentary: "I loved every second!",
          Topic: "Modern",
          isLiked: false,
          likeCount: 2,
        },
      ],
    },
    {
      id: 15,
      PersonName: "Bekzat Sultanov",
      Avatar: "src/assets/pfp_15.svg",
      email: "bekzat@example.com",
      login: "bekzat_s",
      password: "securepassword15",
      favoriteUsers: [7, 12],
      posts: [
        {
          PubDate: "2024-03-09",
          Rating: 3,
          Commentary: "Quite engaging.",
          Topic: "Nature",
          isLiked: false,
          likeCount: 6,
        },
      ],
    },
    {
      id: 16,
      PersonName: "Aruzhan Abilda",
      Avatar: "src/assets/pfp_16.svg",
      email: "aruzhan@example.com",
      login: "aruzhan_a",
      password: "securepassword16",
      favoriteUsers: [3, 14],
      posts: [
        {
          PubDate: "2024-01-12",
          Rating: 4,
          Commentary: "Beautiful scenery.",
          Topic: "Nature",
          isLiked: false,
          likeCount: 8,
        },
      ],
    },
    {
      id: 17,
      PersonName: "Aidar Kassenov",
      Avatar: "src/assets/pfp_17.svg",
      email: "aidar@example.com",
      login: "aidar_k",
      password: "securepassword17",
      favoriteUsers: [4, 9],
      posts: [
        {
          PubDate: "2024-10-08",
          Rating: 2,
          Commentary: "Not my style.",
          Topic: "Adventure",
          isLiked: false,
          likeCount: 0,
        },
      ],
    },
    {
      id: 18,
      PersonName: "Samal Orazbekova",
      Avatar: "src/assets/pfp_18.svg",
      email: "samal@example.com",
      login: "samal_o",
      password: "securepassword18",
      favoriteUsers: [6, 12],
      posts: [
        {
          PubDate: "2024-12-22",
          Rating: 5,
          Commentary: "Incredible journey!",
          Topic: "Adventure",
          isLiked: false,
          likeCount: 9,
        },
      ],
    },
    {
      id: 19,
      PersonName: "Eldar Tursynbayev",
      Avatar: "src/assets/pfp_19.svg",
      email: "eldar@example.com",
      login: "eldar_t",
      password: "securepassword19",
      favoriteUsers: [1, 15],
      posts: [
        {
          PubDate: "2024-05-07",
          Rating: 4,
          Commentary: "A wonderful surprise!",
          Topic: "Nature",
          isLiked: false,
          likeCount: 3,
        },
      ],
    },
    {
      id: 20,
      PersonName: "Mira Khamitova",
      Avatar: "src/assets/pfp_20.svg",
      email: "mira@example.com",
      login: "mira_k",
      password: "securepassword20",
      favoriteUsers: [8, 14],
      posts: [
        {
          PubDate: "2024-10-14",
          Rating: 5,
          Commentary: "Masterpiece!",
          Topic: "Fashion",
          isLiked: false,
          likeCount: 2,
        },
      ],
    },
  ];
  